baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20

  

  # Footer menu
  [[menus.footer]]
    name = "About"
    pageRef = "/about"
    weight = 10
  [[menus.footer]]
    name = "Contact"
    pageRef = "/contact"
    weight = 20
  [[menus.footer]]
    name = 'Tags'
    pageRef = '/tags'
    weight = 30
  [[menus.footer]]
    name = 'Search'
    pageRef = '/search/'
    weight = 40



[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
